artifacts_root : artifacts

data_ingestion:
  root_dir: arifatcs/data_ingestion
  source_url: https://github.com/Divya196/Branching-Tutorial/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion