# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenmlapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenapplication.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_44a1d35746684aaea6cf2d76f7057366 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6bc7060e1ec24d0ea59f0af9172c1ec7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenapplication.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_44a1d35746684aaea6cf2d76f7057366 }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenmlapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3b63e973728b4deca45546bd11c73bd2 }}
        images: 'chickenapplication.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_44a1d35746684aaea6cf2d76f7057366 }}/chicken:${{ github.sha }}'